### ISSUE TITLE
11 failures are detected in the test module "OpeningHours"

### ISSUE THREAD

**Issue by matkoniecz** [mapsme/omim#7026]
```
Running ./opening_hours_tests...
Running 23 test cases...
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1337): error: in "OpeningHours_TestIsActive": check IsActive(rules[0], time) has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1340): error: in "OpeningHours_TestIsActive": check IsActive(rules[1], time) has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1447): error: in "OpeningHours_TestIsActive": check IsActive(rules[0], time) has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1467): error: in "OpeningHours_TestIsActive": check IsActive(rules[0], time) has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1540): error: in "OpeningHours_TestIsOpen": check IsOpen(rules, "2015-07-09 16:50") has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1562): error: in "OpeningHours_TestIsOpen": check IsClosed(rules, "2012-10-08 15:59") has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1575): error: in "OpeningHours_TestIsOpen": check IsOpen(rules, "2015-04-10 07:15") has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1576): error: in "OpeningHours_TestIsOpen": check IsOpen(rules, "2015-05-01 07:15") has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1577): error: in "OpeningHours_TestIsOpen": check IsOpen(rules, "2015-04-11 07:15") has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1596): error: in "OpeningHours_TestIsOpen": check IsOpen(rules, "2017-05-31 23:35") has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1606): error: in "OpeningHours_TestIsOpen": check !IsOpen(rules, "2017-05-31 23:35") has failed

*** 11 failures are detected in the test module "OpeningHours"
```

see https://github.com/mapsme/omim/issues/6890#issuecomment-325816465 for additional examples of failing tests 

It is possible that it is result of failed compilation (in #6890 I am trying to figure how to compile maps.me on Ubuntu 16)

**Comment by matkoniecz** [comment]
@anybody - Is there something that I can do to help in diagnosing this bug?
