### ISSUE TITLE
3party/opening_hours fails to compile with GCC 5.3 and Qt 5.6

### ISSUE THREAD

**Issue by Krakonos** [mapsme/omim#4167]
I'm not really sure what's the issue. I tried compiling without any extra options.
The reported errors are:
```
In file included from parse_opening_hours.cpp:2:0:
opening_hours_parsers.hpp: At global scope:
opening_hours_parsers.hpp:395:30: error: declaration of ‘osmoh::parsing::weekday_selector<Iterator> osmoh::parsing::time_domain<Iterator>::weekday_selector’ [-fpermissive]
   weekday_selector<Iterator> weekday_selector;
                              ^
opening_hours_parsers.hpp:216:7: error: changes meaning of ‘weekday_selector’ from ‘class osmoh::parsing::weekday_selector<Iterator>’ [-fpermissive]
 class weekday_selector : public qi::grammar<Iterator, osmoh::Weekdays(), space_type>
       ^
opening_hours_parsers.hpp:396:27: error: declaration of ‘osmoh::parsing::time_selector<Iterator> osmoh::parsing::time_domain<Iterator>::time_selector’ [-fpermissive]
   time_selector<Iterator> time_selector;
                           ^
opening_hours_parsers.hpp:295:7: error: changes meaning of ‘time_selector’ from ‘class osmoh::parsing::time_selector<Iterator>’ [-fpermissive]
 class time_selector : public qi::grammar<Iterator, osmoh::TTimespans(), space_type>
       ^
opening_hours_parsers.hpp:397:27: error: declaration of ‘osmoh::parsing::year_selector<Iterator> osmoh::parsing::time_domain<Iterator>::year_selector’ [-fpermissive]
   year_selector<Iterator> year_selector;
                           ^
opening_hours_parsers.hpp:40:7: error: changes meaning of ‘year_selector’ from ‘class osmoh::parsing::year_selector<Iterator>’ [-fpermissive]
 class year_selector : public qi::grammar<Iterator, osmoh::TYearRanges(), space_type>
       ^
opening_hours_parsers.hpp:398:28: error: declaration of ‘osmoh::parsing::month_selector<Iterator> osmoh::parsing::time_domain<Iterator>::month_selector’ [-fpermissive]
   month_selector<Iterator> month_selector;
                            ^
opening_hours_parsers.hpp:104:7: error: changes meaning of ‘month_selector’ from ‘class osmoh::parsing::month_selector<Iterator>’ [-fpermissive]
 class month_selector : public qi::grammar<Iterator, TMonthdayRanges(), space_type>
       ^
opening_hours_parsers.hpp:399:27: error: declaration of ‘osmoh::parsing::week_selector<Iterator> osmoh::parsing::time_domain<Iterator>::week_selector’ [-fpermissive]
   week_selector<Iterator> week_selector;
                           ^
opening_hours_parsers.hpp:74:7: error: changes meaning of ‘week_selector’ from ‘class osmoh::parsing::week_selector<Iterator>’ [-fpermissive]
 class week_selector : public qi::grammar<Iterator, osmoh::TWeekRanges(), space_type>
       ^
```

A workaround is to run gcc with -fpermissive, which downgrades the error to a warning, but I'm not sure if it causes any issues. I haven't noticed any obvious issues with the declaration.

G++ was executed like this:

```
g++ -c -pipe -fdata-sections -ffunction-sections -O3 -ffast-math -ffloat-store -g -fPIC -std=gnu++0x -Wall -W -Wno-sign-compare -Wno-strict-aliasing -Wno-unused-parameter -Wno-unused-local-typedef -D_REENTRANT -DRELEASE -D_RELEASE -DNDEBUG -DQT_NO_DEBUG -I. -I../.. -I../../3party/boost -I../../3party/glm -I/usr/lib64/qt5/mkspecs/linux-g++ -o ../../out/release/tmp/opening_hours/parse_opening_hours.o parse_opening_hours.cpp
```
