### PR TITLE
Localads serializer

### PR DESCRIPTION
**Pull request by mgsergio**
@rokuz @syershov

### CODE REVIEW

**Comment by ygorshenin** [comment]
s/localads/local_ads/

File: localads/CMakeLists.txt [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+  campaign.hpp
+  campaign_serialization.cpp
+  campaign_serialization.hpp
+)
+
+add_library(${PROJECT_NAME} ${SRC})
+
+omim_add_pybindings_subdirectory(pylocalads)
+omim_add_test_subdirectory(localads_tests)
+
```
Comment (ygorshenin) [inline localads/CMakeLists.txt]: No need in this blank line.

File: localads/campaign.hpp [hunk 2]
```diff
@@ -0,0 +1,41 @@
+#pragma once
+
+#include "base/assert.hpp"
+
+#include <cstdint>
+#include <string>
+
+
```
Comment (ygorshenin) [inline localads/campaign.hpp]: No need in this blank line.

File: localads/campaign.hpp [hunk 3]
```diff
@@ -0,0 +1,41 @@
+#pragma once
+
+#include "base/assert.hpp"
```
Comment (ygorshenin) [inline localads/campaign.hpp]: Why do we need this?

File: localads/campaign.hpp [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+  // TODO(mgsergio): Provide a working imlpementation.
+  std::string GetIconName() const { return "test-l"; }
+
+  uint32_t m_featureId;
+  uint16_t m_iconId;
+  uint8_t m_daysBeforeExpired;
+  bool m_priorityBit;
+};
+
+inline bool operator==(Campaign const & a, Campaign const & b)
```
Comment (ygorshenin) [inline localads/campaign.hpp]: Do we really need this as external function? Why not to transform this to a method?

File: localads/campaign_serialization.cpp [hunk 5]
```diff
@@ -0,0 +1,84 @@
+#include "localads/campaign_serialization.hpp"
+
+#include "coding/varint.hpp"
+#include "coding/byte_stream.hpp"
```
Comment (ygorshenin) [inline localads/campaign_serialization.cpp]: sort, please.

File: localads/campaign_serialization.cpp [hunk 6]
```diff
@@ -0,0 +1,84 @@
...
+
+#include <vector>
+#include <type_traits>
+#include <cstdint>
```
Comment (ygorshenin) [inline localads/campaign_serialization.cpp]: sort, please

File: localads/campaign_serialization.cpp [hunk 7]
```diff
@@ -0,0 +1,84 @@
...
+
+
```
Comment (ygorshenin) [inline localads/campaign_serialization.cpp]: remove this blank line, please.

File: localads/campaign_serialization.cpp [hunk 8]
```diff
@@ -0,0 +1,84 @@
...
+namespace
+{
+enum class Version
+{
+  unknown = -1,
+  v1 = 0,  // March 2017 (Store featrues ids as varints, use two bytes for
```
Comment (ygorshenin) [inline localads/campaign_serialization.cpp]: featrues?

File: localads/campaign_serialization.cpp [hunk 9]
```diff
@@ -0,0 +1,84 @@
...
+           // both days before expiration and icon id.)
```
Comment (ygorshenin) [inline localads/campaign_serialization.cpp]: You use one byte for days before expiration.

File: localads/campaign_serialization.cpp [hunk 10]
```diff
@@ -0,0 +1,84 @@
...
+  latest = v1
+};
+
+template<typename ByteStream, typename T>
+void Write(ByteStream & s, T t)
+{
+  s.Write(&t, sizeof(T));
```
Comment (ygorshenin) [inline localads/campaign_serialization.cpp]: Please, add enable_if or static_assert that T is pod.

File: localads/campaign_serialization.cpp [hunk 11]
```diff
@@ -0,0 +1,84 @@
...
+}
+
+template<typename T, typename ByteStream>
+T Read(ByteStream & s)
+{
+  T t;
```
Comment (ygorshenin) [inline localads/campaign_serialization.cpp]: Enable if or static assert that T is pod. Please, pass T by reference, not return by value.

File: localads/campaign_serialization.cpp [hunk 12]
```diff
@@ -0,0 +1,84 @@
...
+  s.Read(static_cast<void*>(&t), sizeof(t));
+  return t;
+}
+
+template<typename Integral,
+         typename ByteStream,
+         typename std::enable_if<std::is_integral<Integral>::value, void*>::type = nullptr>
+std::vector<Integral> ReadData(ByteStream & s, size_t chunksNumber)
```
Comment (ygorshenin) [inline localads/campaign_serialization.cpp]: I suggest you to implement a version of varint.hpp:ReadVarUint64Array for a Source.

File: localads/campaign_serialization.cpp [hunk 13]
```diff
@@ -0,0 +1,84 @@
...
+  PushBackByteSink<decltype(buff)> dst(buff);
+  Write(dst, Version::latest);
+  Write(dst, campaigns.size());
+  for (auto const & c : campaigns)
+     WriteVarUint(dst, c.m_featureId);
+  for (auto const & c : campaigns)
+    WriteVarUint(dst, c.m_iconId);
+
+  for (auto const & c : campaigns)
+    Write(dst, c.m_daysBeforeExpired);
```
Comment (ygorshenin) [inline localads/campaign_serialization.cpp]: Do you plan to compress this somehow?

File: localads/campaign_serialization.cpp [hunk 14]
```diff
@@ -0,0 +1,84 @@
...
+  auto const featureIds = ReadData<uint32_t>(src, chunksNumber);
+  auto const icons = ReadData<uint16_t>(src, chunksNumber);
+  auto const expirations = ReadData<uint8_t>(src, chunksNumber);
+
+  CHECK_EQUAL(featureIds.size(), chunksNumber, ());
+  CHECK_EQUAL(icons.size(), chunksNumber, ());
+  CHECK_EQUAL(expirations.size(), chunksNumber, ());
+
+  std::vector<Campaign> campaigns;
+  for (size_t i = 0; i < chunksNumber; ++i)
```
Comment (ygorshenin) [inline localads/campaign_serialization.cpp]: Please, reserve space in campaigns.

File: localads/campaign_serialization.hpp [hunk 15]
```diff
@@ -0,0 +1,13 @@
+#pragma once
+
+#include "localads/campaign.hpp"
+
+#include <cstdint>
+#include <vector>
+
+
```
Comment (ygorshenin) [inline localads/campaign_serialization.hpp]: Remove this blank line, please.

File: localads/localads_tests/CMakeLists.txt [hunk 16]
```diff
@@ -0,0 +1,20 @@
...
+)
+
+omim_add_test(${PROJECT_NAME} ${SRC})
+
+omim_link_libraries(
+  ${PROJECT_NAME}
+  localads
+  coding
+  base
+  platform
```
Comment (ygorshenin) [inline localads/localads_tests/CMakeLists.txt]: Platform uses base, fix the order, please.

File: localads/localads_tests/campaign_serialization_test.cpp [hunk 17]
```diff
@@ -0,0 +1,47 @@
+#include "testing/testing.hpp"
+
+#include "localads/campaign_serialization.hpp"
+
+#include <random>
+#include <vector>
+
+
```
Comment (ygorshenin) [inline localads/localads_tests/campaign_serialization_test.cpp]: Remove this blank line, please.

File: localads/localads_tests/campaign_serialization_test.cpp [hunk 18]
```diff
@@ -0,0 +1,47 @@
...
+using namespace localads;
+
+namespace
+{
+bool TestSerialization(std::vector<Campaign> const & cs)
+{
+  auto const bytes = Serialize(cs);
+  LOG(LINFO, ("Src msg size:", (8+2+1) * cs.size(),
```
Comment (ygorshenin) [inline localads/localads_tests/campaign_serialization_test.cpp]: What this magic constant is? (8 + 2 + 1) ? Clang format please, use sizeof(Campaign) to estimate the original vector size in bytes.

File: localads/localads_tests/campaign_serialization_test.cpp [hunk 19]
```diff
@@ -0,0 +1,47 @@
...
+              "Comporessed size:", bytes.size()));
+  return cs == Deserialize(bytes);
+}
+
+std::vector<Campaign> GenerateRandomCampaigns(size_t number)
+{
+  std::random_device rd;
+  std::mt19937 gen(rd());
+  std::uniform_int_distribution<> featureIds(1, 600000);
```
Comment (ygorshenin) [inline localads/localads_tests/campaign_serialization_test.cpp]: Please, use numeric_limits<decltype(Campaign::m_featureId)>::max(). The same for other fields.

File: localads/localads_tests/campaign_serialization_test.cpp [hunk 20]
```diff
@@ -0,0 +1,47 @@
...
+  std::uniform_int_distribution<> icons(1, 4096);
+  std::uniform_int_distribution<> expirationDays(1, 30);
+
+  std::vector<Campaign> cs;
+  while (number--)
+    cs.emplace_back(featureIds(gen), icons(gen), expirationDays(gen), 0);
```
Comment (ygorshenin) [inline localads/localads_tests/campaign_serialization_test.cpp]: gen is modified three times, for each argument. But the order of evaluation is undefined. Are you sure that it's a good idea? From my point of view, there is an ub.

File: localads/pylocalads/bindings.cpp [hunk 21]
```diff
@@ -0,0 +1,49 @@
+#include "localads/campaign.hpp"
+#include "localads/campaign_serialization.hpp"
+
+// #include "pyhelpers/pair.hpp"
```
Comment (ygorshenin) [inline localads/pylocalads/bindings.cpp]: Do we really need this line?

File: localads/pylocalads/bindings.cpp [hunk 22]
```diff
@@ -0,0 +1,49 @@
...
+#include "pyhelpers/vector_uint8.hpp"
+#include "pyhelpers/vector_list_conversion.hpp"
+
+#include <boost/python.hpp>
+#include <boost/python/suite/indexing/vector_indexing_suite.hpp>
+
+
```
Comment (ygorshenin) [inline localads/pylocalads/bindings.cpp]: Please, remove this blank line.

File: localads/pylocalads/bindings.cpp [hunk 23]
```diff
@@ -0,0 +1,49 @@
...
+}
+
+boost::python::list PyDeserialize(std::vector<uint8_t> const & blob)
+{
+  auto const campaigns = Deserialize(blob);
+  return std_vector_to_python_list(campaigns);
+}
+}  // namespace
+
+
```
Comment (ygorshenin) [inline localads/pylocalads/bindings.cpp]: Please, remove this blank line.

File: pyhelpers/vector_uint8.hpp [hunk 24]
```diff
@@ -2,6 +2,14 @@
 
 #include "std/vector.hpp"
 
+// These headers are necessary for cross-python compilation.
+// Python3 does not have PyString_* methods. One should use PyBytes_* instead.
+// bytesobject.h contains a mappign from PyBytes_* to PyString_*.
```
Comment (ygorshenin) [inline pyhelpers/vector_uint8.hpp]: mappign?

File: pyhelpers/vector_uint8.hpp [hunk 25]
```diff
@@ -2,6 +2,14 @@
...
+// See https://docs.python.org/2/howto/cporting.html for more.
+#include "stdlib.h"
```
Comment (ygorshenin) [inline pyhelpers/vector_uint8.hpp]: cstdlib, please.

File: localads/campaign.hpp (hunk 4 above)
Comment (mgsergio) [inline localads/campaign.hpp]: Why is the external worse? It doesn't have to modify anything it can be an external one.

File: localads/campaign_serialization.cpp (hunk 13 above)
Comment (mgsergio) [inline localads/campaign_serialization.cpp]: Not right no. It's a number between 1 and 30 and fits in one byte. The best way to compress it would be using some 5 free bits of other field.

File: localads/localads_tests/campaign_serialization_test.cpp (hunk 19 above)
Comment (mgsergio) [inline localads/localads_tests/campaign_serialization_test.cpp]: Is value is the approximate number of features in Moscow mwm.
I'll give it a name, but using numeric_limits<decltype(Campaign::m_featureId)>::max() won't do.

File: localads/localads_tests/campaign_serialization_test.cpp (hunk 20 above)
Comment (mgsergio) [inline localads/localads_tests/campaign_serialization_test.cpp]: Why is this a ub? I don't see a problem here until arguments are evaluated asynchronously.

File: localads/pylocalads/bindings.cpp (hunk 21 above)
Comment (mgsergio) [inline localads/pylocalads/bindings.cpp]: nope)

File: localads/campaign.hpp (hunk 2 above)
Comment (mgsergio) [inline localads/campaign.hpp]: done

File: localads/campaign.hpp (hunk 3 above)
Comment (mgsergio) [inline localads/campaign.hpp]: my bad. done

File: localads/campaign_serialization.cpp (hunk 5 above)
Comment (mgsergio) [inline localads/campaign_serialization.cpp]: done.

File: localads/campaign_serialization.cpp (hunk 6 above)
Comment (mgsergio) [inline localads/campaign_serialization.cpp]: done.

File: localads/campaign_serialization.cpp (hunk 7 above)
Comment (mgsergio) [inline localads/campaign_serialization.cpp]: done.

File: localads/campaign_serialization.cpp (hunk 8 above)
Comment (mgsergio) [inline localads/campaign_serialization.cpp]: done.

File: localads/campaign_serialization.cpp (hunk 9 above)
Comment (mgsergio) [inline localads/campaign_serialization.cpp]: done.

File: localads/campaign_serialization.cpp (hunk 14 above)
Comment (mgsergio) [inline localads/campaign_serialization.cpp]: done.

File: localads/campaign_serialization.hpp (hunk 15 above)
Comment (mgsergio) [inline localads/campaign_serialization.hpp]: Done.

File: localads/localads_tests/CMakeLists.txt (hunk 16 above)
Comment (mgsergio) [inline localads/localads_tests/CMakeLists.txt]: done.

File: localads/localads_tests/campaign_serialization_test.cpp (hunk 17 above)
Comment (mgsergio) [inline localads/localads_tests/campaign_serialization_test.cpp]: done.

File: localads/pylocalads/bindings.cpp (hunk 21 above)
Comment (mgsergio) [inline localads/pylocalads/bindings.cpp]: done.

File: localads/pylocalads/bindings.cpp (hunk 22 above)
Comment (mgsergio) [inline localads/pylocalads/bindings.cpp]: done.

File: localads/pylocalads/bindings.cpp (hunk 23 above)
Comment (mgsergio) [inline localads/pylocalads/bindings.cpp]: done.

File: pyhelpers/vector_uint8.hpp (hunk 24 above)
Comment (mgsergio) [inline pyhelpers/vector_uint8.hpp]: done.

File: localads/campaign.hpp (hunk 4 above)
Comment (ygorshenin) [inline localads/campaign.hpp]: Up to you, I'm not insisting.

File: localads/campaign_serialization.cpp (hunk 13 above)
Comment (ygorshenin) [inline localads/campaign_serialization.cpp]: You can use BitWriters, for example. But, up to you.

File: pyhelpers/vector_uint8.hpp (hunk 25 above)
Comment (mgsergio) [inline pyhelpers/vector_uint8.hpp]: Unused. done.

File: localads/localads_tests/campaign_serialization_test.cpp (hunk 20 above)
Comment (mgsergio) [inline localads/localads_tests/campaign_serialization_test.cpp]: Done.

File: localads/localads_tests/campaign_serialization_test.cpp (hunk 18 above)
Comment (mgsergio) [inline localads/localads_tests/campaign_serialization_test.cpp]: Removed.

File: localads/campaign_serialization.cpp [hunk 26]
```diff
@@ -0,0 +1,84 @@
...
+}
+
+template<typename Integral,
+         typename ByteStream,
+         typename std::enable_if<std::is_integral<Integral>::value, void*>::type = nullptr>
+std::vector<Integral> ReadData(ByteStream & s, size_t chunksNumber)
+{
+  std::vector<Integral> result;
+  while (chunksNumber--)
+    result.push_back(ReadVarUint<uint32_t>(s));
```
Comment (mgsergio) [inline localads/campaign_serialization.cpp]: obsolete.

File: localads/campaign_serialization.cpp (hunk 12 above)
Comment (mgsergio) [inline localads/campaign_serialization.cpp]: Done.

File: localads/campaign_serialization.cpp (hunk 11 above)
Comment (mgsergio) [inline localads/campaign_serialization.cpp]: done.

File: localads/campaign_serialization.cpp (hunk 10 above)
Comment (mgsergio) [inline localads/campaign_serialization.cpp]: done.

**Comment by mgsergio** [comment]
PTAL

**Comment by mgsergio** [comment]
PTAL

File: local_ads/pylocal_ads/bindings.cpp [hunk 27]
```diff
@@ -0,0 +1,52 @@
...
+// hence the error. See https://bugs.python.org/issue10910
+#include <locale>
+
+#include "pyhelpers/vector_uint8.hpp"
+#include "pyhelpers/vector_list_conversion.hpp"
+
+#include <boost/python.hpp>
+#include <boost/python/suite/indexing/vector_indexing_suite.hpp>
+
+using namespace localads;
```
Comment (syershov) [inline local_ads/pylocal_ads/bindings.cpp]: s/localads/local_ads/g

File: local_ads/pylocal_ads/bindings.cpp [hunk 28]
```diff
@@ -0,0 +1,52 @@
+#include "local_ads/campaign.hpp"
+#include "local_ads/campaign_serialization.hpp"
+
+// This header shold be included due to a python compilation error.
+// pyport.h overwrites defined macros and replaces it with its own.
+// However, in the OS X c++ libraries, these are not macros but functions,
+// hence the error. See https://bugs.python.org/issue10910
+#include <locale>
```
Comment (syershov) [inline local_ads/pylocal_ads/bindings.cpp]: Please check build with python 2.7

File: local_ads/campaign_serialization.cpp [hunk 29]
```diff
@@ -0,0 +1,104 @@
...
+  auto const expirations = ReadData<uint8_t>(src, chunksNumber);
+
+  CHECK_EQUAL(featureIds.size(), chunksNumber, ());
+  CHECK_EQUAL(icons.size(), chunksNumber, ());
+  CHECK_EQUAL(expirations.size(), chunksNumber, ());
+
+  std::vector<Campaign> campaigns;
+  campaigns.reserve(chunksNumber);
+  for (size_t i = 0; i < chunksNumber; ++i)
+    campaigns.emplace_back(featureIds[i], icons[i], expirations[i], 0);
```
Comment (ygorshenin) [inline local_ads/campaign_serialization.cpp]: false instead of 0, and comment please.

File: local_ads/local_ads_tests/campaign_serialization_test.cpp [hunk 30]
```diff
@@ -0,0 +1,49 @@
...
+  std::uniform_int_distribution<> icons(1, 4096);
+  std::uniform_int_distribution<> expirationDays(1, 30);
+
+  std::vector<Campaign> cs;
+  while (number--)
+  {
+    auto const fid = featureIds(gen);
+    auto const iconid = icons(gen);
+    auto const days = expirationDays(gen);
+    cs.emplace_back(fid, iconid, days, 0);
```
Comment (ygorshenin) [inline local_ads/local_ads_tests/campaign_serialization_test.cpp]: Comment to the constant zero (it should be false, right?)

File: local_ads/pylocal_ads/bindings.cpp (hunk 27 above)
Comment (mgsergio) [inline local_ads/pylocal_ads/bindings.cpp]: Done.

File: local_ads/pylocal_ads/bindings.cpp (hunk 28 above)
Comment (mgsergio) [inline local_ads/pylocal_ads/bindings.cpp]: Checked.

File: local_ads/campaign_serialization.cpp (hunk 29 above)
Comment (mgsergio) [inline local_ads/campaign_serialization.cpp]: Done.

File: local_ads/local_ads_tests/campaign_serialization_test.cpp (hunk 30 above)
Comment (mgsergio) [inline local_ads/local_ads_tests/campaign_serialization_test.cpp]: Done.

**Comment by mgsergio** [comment]
PTAL

**Comment by ygorshenin** [comment]
Conflicts, resove please.

**Comment by mgsergio** [comment]
PTAL

File: local_ads/campaign_serialization.cpp [hunk 31]
```diff
@@ -0,0 +1,111 @@
...
+  std::vector<Integral> result;
+  result.reserve(chunksNumber);
+  auto const streamBegin = s.PtrUC();
+  auto const afterLastReadByte = ReadVarUint64Array(
+      streamBegin,
+      chunksNumber,
+      MakeBackInsertFunctor(result)
+  );
+
+  ASSERT_EQUAL(result.size(), chunksNumber, ());
```
Comment (kshalnev) [inline local_ads/campaign_serialization.cpp]: лучше CHECK_EQUAL. ByteStream может быть файловым, хорошо работать в дебаге и сломаться у какого-то конечного пользователя, assert тогда не остановит от крэша.

File: local_ads/pylocal_ads/bindings.cpp [hunk 32]
```diff
@@ -0,0 +1,52 @@
+#include "local_ads/campaign.hpp"
+#include "local_ads/campaign_serialization.hpp"
+
+// This header shold be included due to a python compilation error.
```
Comment (kshalnev) [inline local_ads/pylocal_ads/bindings.cpp]: shoUld

Comment (mgsergio) [inline local_ads/pylocal_ads/bindings.cpp]: Done.
