### ISSUE TITLE
Build on ubuntu 15.10 failed

### ISSUE THREAD

**Issue by pastukhov** [mapsme/omim#169]
Hi!
I'm getting:
```cpp
../../indexer/search_index_builder.cpp: In constructor ‘{anonymous}::FeatureInserter<TStringsFile>::SkipIndexing::SkipIndexing()’:
../../indexer/search_index_builder.cpp:229:59: error: range-based ‘for’ expression of type ‘std::initializer_list<const char*> []’ has incomplete type
       for (auto const & e : (StringIL[]) { { "entrance" } })
                                                           ^
../../indexer/search_index_builder.cpp:232:70: error: range-based ‘for’ expression of type ‘std::initializer_list<const char*> []’ has incomplete type
       for (auto const & e : (StringIL[]) { { "building", "address" } })
                                                                      ^
../../indexer/search_index_builder.cpp:236:101: error: range-based ‘for’ expression of type ‘std::initializer_list<const char*> []’ has incomplete type
       for (auto const & e : (StringIL[]) { { "highway", "bus_stop" }, { "highway", "speed_camera" } })
                                                                                                     ^
../../indexer/search_index_builder.cpp:240:120: error: range-based ‘for’ expression of type ‘std::initializer_list<const char*> []’ has incomplete type
       for (auto const & e : (StringIL[]) { { "building" }, { "highway" }, { "natural" }, { "waterway" }, { "landuse" } })
                                                                                                                        ^
../../indexer/search_index_builder.cpp:250:30: error: range-based ‘for’ expression of type ‘std::initializer_list<const char*> []’ has incomplete type
         { "railway", "rail" }})
                              ^
Makefile:16300: ошибка выполнения рецепта для цели «../out/release/tmp/indexer/search_index_builder.o»
make[1]: *** [../out/release/tmp/indexer/search_index_builder.o] Ошибка 1
make[1]: выход из каталога «/home/artem/build/omim/build/indexer»
Makefile:337: ошибка выполнения рецепта для цели «sub-indexer-make_first-ordered»
make: *** [sub-indexer-make_first-ordered] Ошибка 2

```

**Comment by Zverik** [comment]
Are you using clang?

**Comment by pastukhov** [comment]
Looks like no, i just have build-essential, kde, qt and other libs.

**Comment by pastukhov** [comment]
Should i use it? which version?

**Comment by pastukhov** [comment]
Found a right INSTALL.md at https://github.com/mapsme/omim/blob/master/docs/INSTALL.md
